<style>
article,
aside,
figure,
footer,
header,
hgroup,
menu,
nav,
section {
    display: block;
}

.hidden {
    display: none;
}
</style>
<div class="card">
    <div class="card-header">
        <h1>New tasting</h1>
    </div>
    <div class="card-body">
        <form action="">
            <fieldset>
                <div class="form-group">
                    <label for="tastingTitle">Title:</label>
                    <input type="text" placeholder="Title" class="form-control" id="tastingTitle" name=" tastingTitle"
                        required /><br />
                </div>
                <div class="form-group">
                    <label for="beerName">Beer name:</label>
                    <input type="text" placeholder="Beer name" class="form-control" id="beerName" name="beerName"
                        required /><br />
                </div>
                <div class="form-group">
                    <label for="beerStyleId">Category:</label>
                    <select class="form-control" id="beerStyleId" name="beerStyleId" required>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>
            </fieldset>
            <fieldset class="hidden">
                <div class="form-check">
                    <label class="form-check-label" for="isBottleOk">Bottle inspection</label>
                    <input type="checkbox" class="form-check-input" id="isBottleOk" name="isBottleOk">
                </div>
                <div class="form-group">
                    <label for="bottleInspectionComment">Comments:</label>
                    <textarea class="form-control" id="bottleInspectionComment" name="bottleInspectionComment"
                        rows="3"></textarea>
                </div>
            </fieldset>
            <fieldset class="hidden">
                <legend>Step 3</legend>
                <input /><br />
            </fieldset>
            <fieldset class="hidden">
                <legend>Step 4</legend>
                <input /><br />
            </fieldset>
            <fieldset class="hidden">
                <legend>Step 5</legend>
                <input /><br />
            </fieldset>
            <div class="card-footer">
                <div class="buttons">
                    <button class="btn btn-secondary btnPrev hidden">Previous</button><button
                        class="btn btn-secondary btnNext">Next</button><input type="submit"
                        class="btn btn-primary btnSubmit hidden" />
                </div>
            </div>
        </form>

    </div>
</div>


<script>
$(document).ready(function() {
    var $fieldsets = $('form fieldset');
    $('.btnNext').click(function(e) {
        e.preventDefault();
        $fieldsets.filter(':visible').slideUp().next().slideDown(shButtons);

    });
    $('.btnPrev').click(function(e) {
        e.preventDefault();
        $fieldsets.filter(':visible').slideUp().prev().slideDown(shButtons);

    });

    function shButtons() {
        console.log($fieldsets.filter(':visible').index());
        if ($fieldsets.filter(':visible').index() > 0) {
            $('.btnPrev').show();
        } else {
            $('.btnPrev').hide();
        }
        console.log(($fieldsets.filter(':visible').index() === $fieldsets.length));
        if ($fieldsets.filter(':visible').index() === $fieldsets.length - 1) {
            $('.btnSubmit').show();
            $('.btnNext').hide();
        } else {
            $('.btnSubmit').hide();
            $('.btnNext').show();
        }
    }
});
</script>