<div class="card">
    <div class="card-header">
        <h1>My tastings</h1>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <table class="table table-striped table-hover table-condensed alignLeft">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Beer Name</th>
                            <th scope="col">Beer Style</th>
                            <th scope="col">Total Score</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($var->tastings as $tasting) {
                        ?>
                        <tr>
                            <th scope="row"><?php echo $tasting->id ?></th>
                            <td><?php echo $tasting->id ?></td>
                            <td><?php echo $tasting->beerName ?></td>
                            <td><?php echo $tasting->beerStyleTitle ?></td>
                            <td>
                                <div class="stars" data-rating="<?php echo $tasting->total / 10 ?>" data-num-stars="5">
                                </div>
                            </td>
                            <td><Strong> <a
                                        href="<?php echo str_replace("#id#", $tasting->id, PAGE_TASTING) ?>">View</a>
                                    |<a class="del" href="">Delete</a></Strong>
                            </td>
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>

                </table>
            </div>
        </div>
        <div class="row d-flex">
            <div class="col-12">
                <div class="mx-auto">
                         <?php
                    echo App::get_partial(
                    PARTIAL_PAGINATION_V4,
                    array(
                        'pages' => $var->pages,
                        'count' => $var->count,
                        'page' => $var->page,
                    )
                );
                ?>
                </div>
             
            </div>
        </div>

    </div>
</div>

<script>
$(document).ready(function() {
    $(".del").click(function(e) {
        e.preventDefault();
        if (!confirm("Do you want to delete")) {
            return false;
        } else {
            window.location.href =
                "<?php echo str_replace("#id#", $tasting->id, PAGE_DELETE_TASTING) ?>";
        }
    });
});
</script>