

<!-- exemple affichage carte -->
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <div class="col">
            <?php
            if(isset($var->tasting)){
                    ?>
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder"><?php $tasting->category ?></h5>
                                        <h4 class="fw-bolder"><?php $tasting->beerName ?></h4>
                                        <div class="rating_stars" data_rating="<?php$tasting->score?>"></div>
                                        <h4 class="fw-bolder"><?php $tasting->creationDate?></h4>
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="<?php str_replace("#id#",$tasting->id,PAGE_SHOW_TASTING) ?>">SHOW</a></div>
                                    </div>
                                </div>
                            </div>
                    <?php
                }
                ?>
        </div>
    </div>
