stages:
  - staging
  - production

staging:
  type: deploy
  stage: staging
  only:
    - main-dev
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/beer-tasting-env-staging.git || true
    - git push -f heroku HEAD:master

production:
  type: deploy
  stage: production
  only:
    - main
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/beer-tasting-env-production.git || true
    - git push -f heroku HEAD:master
