stages:
  - staging
  - production

staging:
  type: deploy
  stage: staging
  script:
    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/beer-tasting-env-staging.git HEAD:master
  only:
    - main-dev

production:
  type: deploy
  stage: production
  script:
    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/beer-tasting-env-production.git HEAD:master
  only:
    - main
