stages:
  - staging
  - production

staging:
  image: ruby:latest
  type: deploy
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - main-dev

production:
  image: ruby:latest
  type: deploy
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
