stages:
  - staging
  - production

staging:
  type: deploy
  stage: staging
  only:
    - main-dev
  script:
    - git push https://git.heroku.com/beer-tasting-env-staging.git main

production:
  type: deploy
  stage: production
  only:
    - main
  script:
    - git push https://git.heroku.com/beer-tasting-env-production.git main
