<?php
$connectedUser = Session::getConnectedUser();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="<?php echo ASSET_FOLDER . "/img/favicon.ico" ?>?v=3" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!--iconify -->
    <script src="https://code.iconify.design/2/2.0.3/iconify.min.js"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="<?php echo CSS_FOLDER . "/styles.css" ?>" rel="stylesheet" />
    <title><?php echo $var->title ?></title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(function() {
            $('.stars').stars();
        });
    </script>
</head>

<body>
    <?php
    if ($connectedUser == null) {
        /* Cas ou l'utilisateur n'est pas connecté, affichez le menu adequat et le content*/
        echo App::get_partial('nav_1', array());
        echo $var->content;
    } else {
    ?>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <?php
                /* Cas ou l'utilisateur est connecté afficher le second menu et le content correspondant de la 
         manière correspondante*/
                echo App::get_partial('nav_2', array());
                ?>
                <div class="col py-3">
                    <?php echo $var->content ?>
                </div>
            </div>
        </div>
    <?php   }  ?>
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5">
            <div class="small text-center text-muted">Copyright &copy; 2021 - Tasting Beer</div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="<?php echo JS_FOLDER . "/scripts.js" ?>"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </script>
</body>

</html>