<div id="userTastings">
    <h4>YOUR LAST TASTINGS</h4>
    <div id="displayUserTastings">
        <?php
        foreach ($var->userTastings as $userTasting) {
            echo App::get_partial(PARTIAL_TASTING, $userTasting);
        }
        ?>
    </div>
    <a class="change_page" href="<?php str_replace("#numberPage#", 1, PAGE_DISPLAY_TASTINGS) ?>">SHOW</a>

</div>

<div class="card">
    <div class="card-header">
        <h4>THE NEW TASTINGS</h4>
    </div>
    <div class="card-body">
        <div id="blockUsersTastings">
            <div id="setOf4UsersTastings">
                <?php
                foreach ($var->lastTastings as $lastTasting) {
                    echo App::get_partial(PARTIALBIS_TASTING, $lastTasting);
                }
                ?>
            </div>
            <a class="change_page" href="<?php str_replace("#numberPage#", 1, PAGE_DISPLAY_TASTINGS) ?>">SHOW</a>
        </div>
    </div>
</div>