<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h2><?php echo beerStyles ?></h2>
                <p><?php echo textBeerStyles ?></p>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <?php
                    foreach ($var->beerStyles as $beerStyle) {
                    ?>
                    <a href="<?php echo str_replace("#id#", $beerStyle->id, PAGE_BEER_STYLE) ?>"
                        class="list-group-item list-group-item-action"><?php echo $beerStyle->title ?></a>
                    <?php
                    }
                    ?>
                </ul>
            </div>
            <div class="mx-auto">
                <?php
                echo App::get_partial(
                    PARTIAL_PAGINATION_V5,
                    array(
                        'pages' => $var->pages,
                        'count' => $var->count,
                        'page' => $var->page,
                    )
                )
                ?>
            </div>
        </div>

    </div>
</div>