<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Rate a beer</h5>
                        <form>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="name">
                                <label for="name">Name</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="category">
                                <label for="categort">Category</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="sub_category">
                                <label for="sub_category">Sub Category</label>
                            </div>
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" value="" id="bottle_inspection">
                                <label class="form-check-label" for="bottle_inspection">Bottle Inspection</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="botlle_inspection_comment">
                                <label for="bottle_inspection_comment">Bottle Inspection Comment</label>
                            </div>
                            <div class="form-group mb-3">
                                <label class="aroma_rating" for="aroma_rating">Aroma Rating</label>
                                <select class="form-control" id="aroma_rating">
                                    <?php
                                        for ($i = 0; $i <= 12; $i++) {
                                            echo "<option value=" . "$i" . ">" . $i . "</option>";
                                        }
                                    ?>
                                </select>
                            </div>
                            <hr class = "d-grid">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>