<div class="dashboard">
    <div class="rectangle ">
        <h4 class="text-center">YOUR TASTINGS</h4>
        <div class="card-body">
            <section class="py-5">
                <?php
                if (empty($var->lastUserTastings) || !isset($var->lastUserTastings)) {
                    echo "<p>No tastings</p>";
                } else {
                    foreach ($var->lastUserTastings as $userTasting) {
                        echo App::get_partial(PARTIAL_TASTING, array("userTasting" => $userTasting));
                    }
                ?>
                <a class="change_page"
                    href="<?php echo str_replace("#userId#", Session::getConnectedUserId(), PAGE_USER_TASTINGS) ?>">
                    <img src="public/assets/img/arrow-right.ico">
                </a>
                <?php
                }
                ?>
            </section>
        </div>
    </div>
    <div class="rectangle">
        <h4 class="text-center">LAST ADDED</h4>
        <div class="card-body">
            <section class="py-5">
                <?php
                if (empty($var->lastTastings) || !isset($var->lastTastings)) {
                    echo "<p>No tastings</p>";
                } else {
                    foreach ($var->lastTastings as $lastTasting) {
                        echo App::get_partial(PARTIAL_ALL_TASTINGS, array("lastTasting" => $lastTasting));
                    }
                ?>
                <a class="change_page" href="<?php echo PAGE_TASTINGS ?>">
                    <img src="public/assets/img/arrow-right.ico">
                </a>
                <?php
                }
                ?>
            </section>
        </div>
    </div>
</div>