<?php
?>
<div class="row">
    <div class="col">
    <?php
    if(isset($tastings)){
        foreach($tastings as $tasting){
            ?>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder"><?php $tasting->title ?></h5>
                                <h5 class="fw-bolder"><?php $tasting->score ?></h5>
                            </div>
                            </div>
                            <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View characteristics</a></div>
                                </div>
                            </div>
                        </div>
            <?php
        }
    }
?>
    </div>

</div>

