<!-- fonction pour le filtre
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#afficherCarte *").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
    });
</script>
-->
<div id="grandRectangle">
    <div>
    <!-- filtre -->
        <input id="myInput" type="text" placeholder="Search..">
        <select id="typefiltre">
            <option value="noFiltrer"selected>Filter</option>
            <option value="recent">more recent</option>
            <option value="older">older</option>
            <option value="bestscore">best score</option>
            <option value="worstscore">worst score</option>
        </select>
        <script>
            var selectElmt = document.getElementById("typeFilter");
            var valeurselectionnee = selectElmt.options[selectElmt.selectedIndex].value;
            str_replace("#filter#",valeurselectionee,PAGE_DISPLAY_TASTINGS)
        </script>
    </div>
    <!-- carte à afficher -->
    <div id="afficherCarte">
        <?php
            foreach($tastings as $tasting){
                echo App::get_partial(PARTIAL_TASTING,$tasting);
            }
        ?>
    </div>
    <!-- pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",$_GET['numberPage']-1,PAGE_DISPLAY_TASTINGS) ?>">Previous</a></li>
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",1,PAGE_DISPLAY_TASTINGS) ?>">1</a></li>
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",2,PAGE_DISPLAY_TASTINGS) ?>">2</a></li>
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",3,PAGE_DISPLAY_TASTINGS) ?>">3</a></li>
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",4,PAGE_DISPLAY_TASTINGS) ?>">4</a></li>
            <li class="page-item"><a class="page-link" href="<?php str_replace("#numberPage#",$_GET['numberPage']-1,PAGE_DISPLAY_TASTINGS) ?>">Next</a></li>
        </ul>
    </nav>
</div>