        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Votre plateforme pour enregistrer vos degustations de bières</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5"><strong>Tasting beer</strong> est l'ideal pour enregistrer ses degustations de bières selon les normes BJCP et consulter d'autres degustations de bieres.</p>
                        <a class="btn btn-primary btn-xl" href="#about">Consultez les degustations</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">Enregistrer votre degustation</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4"> <strong>Tasting beer</strong> offre à tous degustateurs la confidentialité et l'assurance que leurs degustations ne pourront etre modifier que par eux.</p>
                        <a class="btn btn-light btn-xl" href="#services">S'inscrire</a>
                    </div>
                </div>
            </div>
        </section>