<!-- Alert-->
<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <?php
                    if (!empty($var->errors)) {
                        foreach ($var->errors as $error) {
                    ?>
                    <div class="alert alert-danger" role="alert">
                        <?php echo $error; ?>
                    </div>
                    <?php
                        }
                    }
                    ?>
                    <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
                    <form action="" method="POST">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                name="email">
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="floatingPassword" placeholder="Password"
                                name="password">
                            <label for="floatingPassword">Password</label>
                        </div>

                        <div class="form-check mb-3">
                            <input class="form-check-input" type="checkbox" value="true" id="rememberPasswordCheck"
                                name="remenberMe">
                            <label class="form-check-label" for="rememberPasswordCheck">
                                Remember password
                            </label>
                        </div>
                        <div class="g-recaptcha offset-3" data-sitekey="6LcV_ysdAAAAAGWDDP703-b3WU7qiengcMI5aE7g"></div>
                        <!-- "6LcyDSwdAAAAAFT7QOdQTsZ4hTPnKC3DO-KTJANO" pour le site en prod -->
                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign
                                in</button>
                        </div>
                        <hr class="my-4">
                        <label class="text-center">
                            <a href="">you don't have an account?</a> or <a href="">Forgot Password ?</a>
                        </label>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>