<!-- Alert-->
<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5">
                    <div class="alert alert-danger hidden" id="errorContainer" role="alert">
                    </div>
                    <h5 class="card-title text-center mb-5 fw-light fs-5">SIGN IN</h5>
                    <form id="signinForm" action="" method="POST">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="email" placeholder="name@example.com"
                                name="email" required>
                            <label for="email">Email address</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="password" placeholder="Password"
                                name="password" required>
                            <label for="password">Password</label>
                            <a href="">Forgot
                                Password ?</a>
                        </div>


                        <!--
                        <div class="form-check mb-3">
                            <input class="form-check-input" type="checkbox" value="true" id="rememberPasswordCheck"
                                name="remenberMe">
                            <label class="form-check-label" for="rememberPasswordCheck">
                                Remember password
                            </label>
                        </div>-->
                        <div class="g-recaptcha offset-3" data-sitekey="6LcV_ysdAAAAAGWDDP703-b3WU7qiengcMI5aE7g"></div>
                        <!-- "6LcyDSwdAAAAAFT7QOdQTsZ4hTPnKC3DO-KTJANO" pour le site en prod -->
                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign
                                in</button>
                        </div>
                        <hr class="my-4">
                        <label class="text-center">
                            <a href="<?php echo PAGE_SIGNUP ?>">You don't have an account?</a>
                        </label>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    function setupMessagesContainer() {
        $('#errorContainer').empty();
        $('#errorContainer').hide();
    }
    setupMessagesContainer();
    $("#signinForm").submit(function(e) {
        e.preventDefault();
        const email = $("#email").val();
        const password = $("#password").val();
        $.ajax({
            type: "POST",
            url: "",
            data: {
                "email": email,
                'password': password
            },
            dataType: 'json',
            success: function(feedback) {
                setupMessagesContainer();
                if (feedback.status == "success") {
                    window.location = "<?php echo PAGE_DASHBOARD ?>";
                } else if (feedback.status == "error") {
                    $('#errorContainer').show();
                    $('#errorContainer').append("<ul>");
                    jQuery.each(feedback.message, function(index, item) {
                        $('#errorContainer').append("<li>" + item + "</li>");
                    });
                    $('#errorContainer').append("</ul>");
                }
            }
            /*,
                        error: function(XMLHttpRequest, textStatus, errorThrown) {
                            alert("Status: " + textStatus);
                            alert("Error: " + errorThrown);
                        }
                        */
        })
    });
});
</script>