<div class="row">
    <div class="col-12">
        <div class="card no-border">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                  Liste des degustations
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-condensed alignLeft">
                        <thead>
                            <tr>
                                <th scope="col"><?php echo title ?></th>
                                <th scope="col"><?php echo beerName ?></th>
                                <th scope="col"><?php echo beerStyle ?></th>
                                <th scope="col"><?php echo score ?></th>
                                <th scope="col"><?php echo creationDate ?></th>
                                <th scope="col">Auuteur</th>
                                <th scope="col"><?php echo actions ?></th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="score" data-type="table" data-score="0/50">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="mx-auto">

            </div>
        </div>
    </div>
</div>
