<fieldset class="hidden">
    <div class="form-check">
        <label class="form-check-label" for="<?php echo Tasting::IS_BOTTLE_OK ?>">Bottle inspection</label>
        <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_BOTTLE_OK ?>"
            name="<?php echo Tasting::IS_BOTTLE_OK ?>">
    </div>
    <div class="form-group">
        <label for="<?php echo Tasting::BOTTLE_INSPECTION_COMMENT ?>">Comments:</label>
        <textarea class="form-control" id="<?php echo Tasting::BOTTLE_INSPECTION_COMMENT ?>"
            name="<?php echo Tasting::BOTTLE_INSPECTION_COMMENT ?>" rows="2"></textarea>
    </div>
</fieldset>