<fieldset class="hidden">
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACETALDEHYDE ?>">Acetaldehyde</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACETALDEHYDE ?>"
                    name="<?php echo Tasting::IS_ACETALDEHYDE ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_ALCOHOLIC ?>">Alcoholic</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ALCOHOLIC ?>"
                    name="<?php echo Tasting::IS_ALCOHOLIC ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_ASTRINGENT ?>">Astringent</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ASTRINGENT ?>"
                    name="<?php echo Tasting::IS_ASTRINGENT ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_DIACETYL ?>">Diacetyl</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DIACETYL ?>"
                    name="<?php echo Tasting::IS_DIACETYL ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_DMS ?>">DMS (dimethyl
                    sufide)</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DMS ?>"
                    name="<?php echo Tasting::IS_DMS ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_ESTERY ?>">Estery</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ESTERY ?>"
                    name="<?php echo Tasting::IS_ESTERY ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_GRASSY ?>">Grassy</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_GRASSY ?>"
                    name="<?php echo Tasting::IS_GRASSY ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_LIGHT_STRUCK ?>">Light-Struck</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_LIGHT_STRUCK ?>"
                    name="<?php echo Tasting::IS_LIGHT_STRUCK ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_METALLIC ?>">Metallic</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_METALLIC ?>"
                    name="<?php echo Tasting::IS_METALLIC ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_MUSTY ?>">Musty</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_MUSTY ?>"
                    name="<?php echo Tasting::IS_MUSTY ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_OXIDIZED ?>">Oxidized</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_OXIDIZED ?>"
                    name="<?php echo Tasting::IS_OXIDIZED ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_PHENOLIC ?>">Phenolic</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_PHENOLIC ?>"
                    name="<?php echo Tasting::IS_PHENOLIC ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_SOLVENT ?>">Solvent</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SOLVENT ?>"
                    name="<?php echo Tasting::IS_SOLVENT ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACIDIC ?>">Sour/Acidic</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACIDIC ?>"
                    name="<?php echo Tasting::IS_ACIDIC ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_SULFUR ?>">Sulfur</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SULFUR ?>"
                    name="<?php echo Tasting::IS_SULFUR ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_VEGETAL ?>">Vegetal</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_VEGETAL ?>"
                    name="<?php echo Tasting::IS_VEGETAL ?>">
            </div>
        </div>
        <div class="col">
            <div class="form-check">
                <label class="form-check-label" for="<?php echo Tasting::IS_YEASTY ?>">Yeasty</label>
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_YEASTY ?>"
                    name="<?php echo Tasting::IS_YEASTY ?>">
            </div>
        </div>
    </div>
</fieldset>