<fieldset>
    <div class="form-floating mb-3">
        <input type="text" placeholder="Title" class="form-control requiredInput required" id="tastingTitle"
            name="tastingTitle" />
        <label for="tastingTitle">Title</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" placeholder="Beer name" class="form-control required" id="beerName" name="beerName" />
        <label for="beerName">Beer name</label>
    </div>
    <div class="form-floating mb-3">
        <select class="form-control" id="beerStyleId" name="beerStyleId">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
        <label for="beerStyleId">Category</label>
    </div>
</fieldset>