<fieldset class="hidden">
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACETALDEHYDE ?>"
                    name="<?php echo Tasting::IS_ACETALDEHYDE ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACETALDEHYDE ?>">Acetaldehyde</label>     
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ALCOHOLIC ?>"
                    name="<?php echo Tasting::IS_ALCOHOLIC ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ALCOHOLIC ?>">Alcoholic</label>    
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ASTRINGENT ?>"
                    name="<?php echo Tasting::IS_ASTRINGENT ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ASTRINGENT ?>">Astringent</label>    
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DIACETYL ?>"
                    name="<?php echo Tasting::IS_DIACETYL ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_DIACETYL ?>">Diacetyl</label>     
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_DMS ?>"
                    name="<?php echo Tasting::IS_DMS ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_DMS ?>">DMS (dimethyl
                    sufide)</label>      
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ESTERY ?>"
                    name="<?php echo Tasting::IS_ESTERY ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ESTERY ?>">Estery</label>    
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_GRASSY ?>"
                    name="<?php echo Tasting::IS_GRASSY ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_GRASSY ?>">Grassy</label>    
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_LIGHT_STRUCK ?>"
                    name="<?php echo Tasting::IS_LIGHT_STRUCK ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_LIGHT_STRUCK ?>">Light-Struck</label>     
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_METALLIC ?>"
                    name="<?php echo Tasting::IS_METALLIC ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_METALLIC ?>">Metallic</label>
    
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_MUSTY ?>"
                    name="<?php echo Tasting::IS_MUSTY ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_MUSTY ?>">Musty</label>    
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_OXIDIZED ?>"
                    name="<?php echo Tasting::IS_OXIDIZED ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_OXIDIZED ?>">Oxidized</label>    
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">                
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_PHENOLIC ?>"
                    name="<?php echo Tasting::IS_PHENOLIC ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_PHENOLIC ?>">Phenolic</label>    
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SOLVENT ?>"
                    name="<?php echo Tasting::IS_SOLVENT ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_SOLVENT ?>">Solvent</label>    
            </div>
        </div>
        <div class="col-2"></div>
        <div class="col-5">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_ACIDIC ?>"
                    name="<?php echo Tasting::IS_ACIDIC ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_ACIDIC ?>">Sour/Acidic</label>    
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_SULFUR ?>"
                    name="<?php echo Tasting::IS_SULFUR ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_SULFUR ?>">Sulfur</label>    
            </div>
        </div>
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_VEGETAL ?>"
                    name="<?php echo Tasting::IS_VEGETAL ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_VEGETAL ?>">Vegetal</label>    
            </div>
        </div>
        <div class="col-4">
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="<?php echo Tasting::IS_YEASTY ?>"
                    name="<?php echo Tasting::IS_YEASTY ?>">
                <label class="form-check-label" for="<?php echo Tasting::IS_YEASTY ?>">Yeasty</label>    
            </div>
        </div>
    </div>
</fieldset>