<fieldset class="hidden">
    <div class="row">
        <div class="col">
             <div class="d-flex justify-content-between align-items-center mb-3">
                    <label class="form-check-label" for="">Stylistic Accuracy</label>
                </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <select class="form-control required" id=""
                    name="" 
                    data-toggle="tooltip" data-placement="top" title="<?php echo STYLISTIC_MESSAGE ?>">
                    <option value=1>1</option>
                    <option value=2>2</option>
                    <option value=3>3</option>
                    <option value=4>4</option>
                </select>
                <label for="">Rating</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
             <div class="d-flex justify-content-between align-items-center mb-3">
                    <label class="form-check-label" for="">Technical Merit</label>
                </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <select class="form-control required" id=""
                    name=""
                    data-toggle="tooltip" data-placement="top" title="<?php echo TECHNICALMERIT_MESSAGE ?>">
                    <option value=1>1</option>
                    <option value=2>2</option>
                    <option value=3>3</option>
                    <option value=4>4</option>
                </select>
                <label for="">Rating</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
             <div class="d-flex justify-content-between align-items-center mb-3">
                    <label class="form-check-label" for="">Intangibles</label>
                </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <select class="form-control required" id=""
                    name=""
                    data-toggle="tooltip" data-placement="top" title="<?php echo INTANGIBLES_MESSAGE ?>">
                    <option value=1>1</option>
                    <option value=2>2</option>
                    <option value=3>3</option>
                    <option value=4>4</option>
                </select>
                <label for="">Rating</label>
            </div>
        </div>
    </div>
</fieldset>