<fieldset>
    <div class="form-group">
        <label for="tastingTitle">Title:</label>
        <input type="text" placeholder="Title" class="form-control requiredInput required" id="tastingTitle"
            name=" tastingTitle" /><br />
    </div>
    <div class="form-group">
        <label for="beerName">Beer name:</label>
        <input type="text" placeholder="Beer name" class="form-control required" id="beerName" name="beerName" /><br />
    </div>
    <div class="form-group">
        <label for="beerStyleId">Category:</label>
        <select class="form-control" id="beerStyleId" name="beerStyleId">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
</fieldset>