<fieldset class="hidden">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <label class="form-check-label" for="<?php echo Tasting::STYLISTIC_ACCURACY ?>">Stylistic Accuracy</label>
        </div>
        <div class="col-md-6 col-xs-12">
            <input name=" <?php echo Tasting::STYLISTIC_ACCURACY ?>" id="<?php echo Tasting::STYLISTIC_ACCURACY ?>"
                type="range" class="form-range" min="1" max="4" step="1" required>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <label class=" form-check-label" for="<?php echo Tasting::TECHNICAL_MERIT ?>">Technical Merit</label>
        </div>
        <div class="col-md-6 col-xs-12">
            <input name=" <?php echo Tasting::TECHNICAL_MERIT ?>" id=" <?php echo Tasting::TECHNICAL_MERIT ?>"
                class="form-range" min="1" max="4" step="1" type="range" required>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <label class=" form-check-label" for="<?php echo Tasting::INTANGIBLES ?>">Intangibles</label>
        </div>
        <div class="col-md-6 col-xs-12">
            <input name=" <?php echo Tasting::INTANGIBLES ?>" id="<?php echo Tasting::INTANGIBLES ?>" type="range"
                class="form-range" min="1" max="4" step="1" required>
        </div>
    </div>
</fieldset>