<!--
<nav id="mainNav" class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-beer">
    <div
        class="d-flexbis clearflix flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a href="<?php echo PAGE_DASHBOARD ?>"
            class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none"
            data-toggle="tooltip" data-placement="right" title="Dashboard">
            <span class="iconify" data-icon="fxemoji:beermug" data-width="100" data-height="100"
                alt="Beer Tasting">Beer-Tasting</span>
        </a>
        <ul class="nav flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start " id="menu">
            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_PROFILE ?>" class="nav-link px-0 align-middle" data-toggle="tooltip"
                    data-placement="right" title="My account">
                    <span class="iconify" style="color: black;" data-icon="iconoir:profile-circled" data-width="100"
                        data-height="100"></span> </a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3" data-toggle="tooltip"
                data-placement="right" title="Add a new degustation">
                <a href="<?php echo PAGE_TASTINGS_ADD ?>" class="nav-link px-0 align-middle">
                    <span class="iconify" style="color: black;" data-icon="carbon:folder-add" data-width="100"
                        data-height="100"> </span> </a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_TASTINGS ?>" class="nav-link px-0 align-middle" data-toggle="tooltip"
                    data-placement="right" title="Show tastings">
                    <span class="iconify" style="color: black;" data-icon="ant-design:eye-twotone" data-width="100"
                        data-height="100"></span></a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_USER_TASTINGS_MANAGEMENT ?>" class="nav-link px-0 align-middle"
                    data-toggle="tooltip" data-placement="right" title="Manage my tastings">
                    <span class="iconify" style="color: black;" data-icon="el:cogs" data-width="100"
                        data-height="100"></span></a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_LOGOUT ?>" class="nav-link px-0 align-middle" data-toggle="tooltip"
                    data-placement="right" title="LogOut">
                    <span class="iconify" style="color: black;" data-icon="fa-solid:power-off" data-width="100"
                        data-height="100"> </span> </a>
            </li>

        </ul>
    </div>
</nav>
-->
<div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
    <a href="<?php echo PAGE_DASHBOARD ?>"
        class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-5">B<span class="d-none d-sm-inline">rand</span></span>
    </a>
    <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start"
        id="menu">
        <li class="nav-item">
            <a href="<?php echo PAGE_PROFILE ?>" class="nav-link px-sm-0 px-2  text-white">
                <i class="bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline">Profile</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="<?php echo PAGE_TASTINGS_ADD ?>" class="nav-link px-sm-0 px-2  text-white">
                <i class="fs-5 bi-file-plus"></i><span class="ms-1 d-none d-sm-inline">Add</span>
            </a>
        </li>
        <li>
            <a href="<?php echo PAGE_TASTINGS ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-eye"></i><span class="ms-1 d-none d-sm-inline">View</span></a>
        </li>
        <li>
            <a href="<?php echo PAGE_USER_TASTINGS_MANAGEMENT ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-gear"></i><span class="ms-1 d-none d-sm-inline">Manage</span></a>
        </li>
        <li>
            <a href="<?php echo PAGE_LOGOUT ?>" class="nav-link px-sm-0 px-2 text-white">
                <i class="fs-5 bi bi-box-arrow-right"></i><span class="ms-1 d-none d-sm-inline">Logout</span></a>
        </li>
    </ul>
</div>