<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-beer">
    <div
        class="d-flexbis clearflix flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a href="<?php echo PAGE_DASHBOARD ?>"
            class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none"
            data-toggle="tooltip" data-placement="right" title="Dashboard">
            <span class="iconify" data-icon="fxemoji:beermug" data-width="100" data-height="100"
                alt="Beer Tasting">Beer-Tasting</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start " id="menu">
            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="#" data-bs-toggle="collapse" class="nav-link px-0 align-middle" data-toggle="tooltip"
                    data-placement="right" title="Show your profile">
                    <span class="iconify" style="color: black;" data-icon="iconoir:profile-circled" data-width="100"
                        data-height="100"></span> </a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="#" data-bs-toggle="collapse" class="nav-link px-0 align-middle" data-toggle="tooltip"
                    data-placement="right" title="Add a new degustation">
                    <span class="iconify" style="color: black;" data-icon="carbon:folder-add" data-width="100"
                        data-height="100"> </span> </a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_TASTINGS ?>" data-bs-toggle="collapse" class="nav-link px-0 align-middle"
                    data-toggle="tooltip" data-placement="right" title="Show the degustations">
                    <span class="iconify" style="color: black;" data-icon="ant-design:eye-twotone" data-width="100"
                        data-height="100"></span></a>
            </li>

            <li class="nav-item list-group-item-action list-group-item-light p-3">
                <a href="<?php echo PAGE_LOGOUT ?>" data-bs-toggle="collapse" class="nav-link px-0 align-middle"
                    data-toggle="tooltip" data-placement="right" title="LogOut">
                    <span class="iconify" style="color: black;" data-icon="fa-solid:power-off" data-width="100"
                        data-height="100"> </span> </a>
            </li>

        </ul>
    </div>
</div>