<?php
$count = $var->count;
$page = $var->page;
$pages = $var->pages;
$id = Session::getConnectedUserId();
?>
<div class="inline-block">
    <strong><?php echo (int)$count ?> résultat<?php echo ((int)$count > 1) ? 's' : '' ?></strong>
</div>
<?php
if ($count > 0) {
?>
<ul class="pagination inline-block">
    <?php
        if ($page !== 1) {
        ?>
    <li class="page-item"><a class="page-link"
            href="<?php echo str_replace(array("#userId#", "#page#"), array($id, $page - 1), PAGE_USER_TASTINGS_BY_PAGE) ?>">Précédent</a>
    </li>
    <?php
        }
        ?>
    <?php for ($i = 1; $i <= $pages; $i++) :
            if ($i >= 5) {
                break;
            }
        ?>
    <li class="page-item"><a class="page-link"
            href="<?php echo str_replace(array("#userId#", "#page#"), array($id, $i), PAGE_USER_TASTINGS_BY_PAGE) ?>"><?php echo $i ?></a>
    </li>
    <?php endfor; ?>
    <?php
        if ($page != $pages) {
        ?>
    <li class="page-item"><a class="page-link"
            href="<?php echo str_replace(array("#userId#", "#page#"), array($id, $page + 1), PAGE_USER_TASTINGS_BY_PAGE) ?>">Suivant</a>
    </li>
    <?php
        }
        ?>
</ul>
<?php
}
?>