<!-- exemple affichage carte -->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div id="fondCard">
                <?php
                if (isset($var->lastTasting)) {
                    $lastTasting = $var->lastTasting;
                ?>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder" id="beerCategory"><?php $lastTasting->category ?></h5>
                                <h4 class="fw-bolder" id="beerName"><?php $lastTasting->beerName ?></h4>
                                <h4 class="fw-bolder" id="userName"><?php $lastTasting->userName ?></h4>
                                <div class="rating_stars" data_rating="<?php $lastTasting->score ?>"></div>
                                <h4 class="fw-bolder" id="date"><?php $lastTasting->creationDate ?></h4>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent" id="boutonShowMore">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" id="boutonText"
                                    href="<?php str_replace("#id#", $lastTasting->id, PAGE_TASTING) ?>">SHOW</a></div>
                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
            </div>
        </div>
    </div>
</section>