<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5" id="cardboard">                 
                    
                    <!-- Test Page Genere en JS -->
                    
                    <script>

                        //<h5 class="card-title text-center mb-5 fw-light fs-5">Rate a beer</h5>

                        var page = 1;
                        var title = "";
                        var title2 = "";
                        var onFirstPage = true;
                        let elt = document.getElementById("cardboard");
                        const h5 = document.createElement("h5");
                        h5.setAttribute("class", "card-title text-center mb-5 fw-light fs-5");
                        h5.innerHTML = "Rate a beer (1/5)";
                        elt.appendChild(h5);                 
                        const form1 = document.createElement("form");                       
                        form1.setAttribute("id", "beer_form");
                        elt.appendChild(form1);

                        page1();
                        button();
                        listen();

                        function page1(){
                            const div1 = document.createElement("div");
                            div1.setAttribute("class", "form-floating mb-3");

                            const input1 = document.createElement("input");
                            input1.setAttribute("type", "text");
                            input1.setAttribute("class", "form-control");
                            input1.setAttribute("id", "title");

                            const label1 = document.createElement("label");
                            label1.setAttribute("for", "title");
                            label1.innerHTML = "Title";
                            
                            div1.appendChild(input1);
                            div1.appendChild(label1);
                            form1.appendChild(div1);

                            document.getElementById("title").addEventListener(
                                "input", function(e) {
                                    title = e.target.value;
                                }
                            );
                        }

                        function page2(){
                            const div1 = document.createElement("div");
                            div1.setAttribute("class", "form-floating mb-3");

                            const input1 = document.createElement("input");
                            input1.setAttribute("type", "text");
                            input1.setAttribute("class", "form-control");
                            input1.setAttribute("id", "title2");

                            const label1 = document.createElement("label");
                            label1.setAttribute("for", "title2");
                            label1.innerHTML = title;
                            
                            div1.appendChild(input1);
                            div1.appendChild(label1);
                            form1.appendChild(div1);

                            document.getElementById("title2").addEventListener(
                                "input", function(e) {
                                    title2 = e.target.value;
                                }
                            ); 
                        }

                        function button(){
                            const button = document.createElement("div");
                            button.setAttribute("class", "form-floating mb-3");
                                                     
                            const next = document.createElement("input");
                            next.setAttribute("class", "favorite styled");
                            next.setAttribute("type", "button");
                            next.setAttribute("id", "next");
                            next.setAttribute("value", "Next");
                            
                            const prev = document.createElement("input");
                            prev.setAttribute("class", "favorite styled");
                            prev.setAttribute("type", "button");
                            prev.setAttribute("id", "prev");
                            prev.setAttribute("value", "Previous");

                            if(page!=1){button.appendChild(prev);}
                            if(page!=5){button.appendChild(next);}
                            form1.appendChild(button);
                        }

                        function listen(){
                            if(page!=5){
                                document.getElementById("next").addEventListener('click', function() {
                                    if(page < 5){
                                        page++;
                                        pageChange(page);                                
                                    }
                                });
                            }
                            if(page!=1){
                                document.getElementById("prev").addEventListener('click', function() {  
                                    if(page > 1){
                                        page--;
                                        pageChange(page);    
                                    }                         
                                });
                            }
                        }

                        function pageChange(page){
                            if(page == 1){ 
                                h5.innerHTML = "Rate a beer (1/5)";
                                form1.innerHTML = "";
                                page1();
                                button();
                                listen();
                                
                            }
                            if(page == 2){
                                h5.innerHTML = "Rate a beer (2/5)";
                                form1.innerHTML = "";
                                page2();
                                button();  
                                listen();                      
                            }
                            if(page == 3){
                                h5.innerHTML = "Rate a beer (3/5) " + title2;
                                form1.innerHTML = "";
                                page2();
                                button();
                                listen();
                            }
                            if(page == 4){
                                h5.innerHTML = "Rate a beer (4/5)";
                                form1.innerHTML = "";
                                page2();
                                button();
                                listen();
                            }
                            if(page == 5){
                                h5.innerHTML = "Rate a beer (5/5)";
                                form1.innerHTML = "";
                                page2();
                                button();
                                listen();                  
                            }   
                        }
        
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>