<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5" id="cardboard">                 
                    
                    <!-- Test Page Genere en JS -->
                    
                    <script>

                        //<h5 class="card-title text-center mb-5 fw-light fs-5">Rate a beer</h5>

                        var page = 1;

                        var title = "";
                        var name = "";
                        var category = "";

                        let elt = document.getElementById("cardboard");
                        const h5 = document.createElement("h5");
                        h5.setAttribute("class", "card-title text-center mb-5 fw-light fs-5");
                        h5.innerHTML = "Rate a beer (1/5)";
                        elt.appendChild(h5);                 
                        const form1 = document.createElement("form");                       
                        form1.setAttribute("id", "beer_form");
                        elt.appendChild(form1);

                        page1();
                        button();
                        listen();

                        function page1(){
                            form1.innerHTML =         
                            '<div class="form-floating mb-3">'+
                                '<input type="text" class="form-control" id="title">'+
                                '<label for="title">Title</label>'+
                            '</div>'+
                            '<div class="form-floating mb-3">'+
                                '<input type="text" class="form-control" id="name">'+
                                '<label for="name">Name</label>'+
                            '</div>'+
                            '<div class="form-floating mb-3">'+
                                '<input type="text" class="form-control" id="category">'+
                                '<label for="category">Category</label>'+
                            '</div>';
                        
                            document.getElementById("title").addEventListener(
                                "input", function(e) {title = e.target.value;}
                            );
                            document.getElementById("name").addEventListener(
                                "input", function(e) {name = e.target.value;}
                            );
                            document.getElementById("category").addEventListener(
                                "input", function(e) {category = e.target.value;}
                            );

                        
                        }

                        function page2(){
                            
                            form1.innerHTML =    
                                '<div class="form-check mb-3">'+
                                    '<input class="form-check-input" type="checkbox" value="" id="bottle_inspection">'+
                                    '<label class="form-check-label" for="bottle_inspection">Bottle Inspection</label>'+
                                '</div>'+
                                '<div class="form-floating mb-3">'+
                                    '<input type="text" class="form-control" id="botlle_inspection_comment">'+
                                    '<label for="bottle_inspection_comment">Bottle Inspection Comment</label>'+
                                '</div>';
                            document.getElementById("bottle_inspection").addEventListener(
                                "input", function(e) {
                                    title2 = e.target.value;
                                }
                            ); 
                        }

                        function page3(){


                            form1.innerHTML =
                            '<table><tr><td>Aroma</td><td>Rating</td></tr><tr><td>' +        
                            '<div class="form-floating mb-3">'+
                                '<input type="text" class="form-control" id="bottle_inspection_comment">'+
                                '<label for="bottle_inspection_comment">Bottle Inspection Comment</label>'+
                            '</div></td>'+
                            '<td><div class="form-floating mb-3">'+
                                '<select class="form-control" id="bottle_inpection">'+
                                    '<option value=0>0' +
                                    '<option value=1>1' +
                                    '<option value=2>2' +
                                    '<option value=3>3' +
                                    '<option value=4>4' +
                                    '<option value=5>5' +
                                    '<option value=6>6' +
                                    '<option value=7>7' +
                                    '<option value=8>8' +
                                    '<option value=9>9' +
                                    '<option value=10>10' +
                                    '<option value=11>11' +
                                    '<option value=12>12' +                                  
                                '</select>' +
                            '</div></td>' +
                            '<tr><td>Appearance</td><td>Rating</td></tr><tr><td>' +
                            '<div class="form-floating mb-3">'+
                                '<input type="text" class="form-control" id="appearance_comment">'+
                                '<label for="bottle_inspection_comment">Comment</label>'+
                            '</div></td>'+
                            '<td><div class="form-floating mb-3">'+
                                '<select class="form-control" id="bottle_inpection">'+
                                    '<option value=0>0' +
                                    '<option value=1>1' +
                                    '<option value=2>2' +
                                    '<option value=3>3' +                             
                                '</select>' +
                            '</div></td></tr>' +
                            '</table>';
                        }

                        function button(){
                            const button = document.createElement("div");
                            button.setAttribute("class", "form-floating mb-3");
                                                     
                            const next = document.createElement("input");
                            next.setAttribute("class", "favorite styled");
                            next.setAttribute("type", "button");
                            next.setAttribute("id", "next");
                            next.setAttribute("value", "Next");
                            
                            const prev = document.createElement("input");
                            prev.setAttribute("class", "favorite styled");
                            prev.setAttribute("type", "button");
                            prev.setAttribute("id", "prev");
                            prev.setAttribute("value", "Previous");

                            if(page!=1){button.appendChild(prev);}
                            if(page!=5){button.appendChild(next);}
                            form1.appendChild(button);
                        }

                        function listen(){
                            if(page!=5){
                                document.getElementById("next").addEventListener('click', function() {
                                    if(page < 5){
                                        page++;
                                        pageChange(page);                                
                                    }
                                });
                            }
                            if(page!=1){
                                document.getElementById("prev").addEventListener('click', function() {  
                                    if(page > 1){
                                        page--;
                                        pageChange(page);    
                                    }                         
                                });
                            }
                        }

                        function pageChange(page){
                            if(page == 1){ 
                                h5.innerHTML = "Rate a beer (1/5)";
                                form1.innerHTML = "";
                                page1();
                                button();
                                listen();
                                
                            }
                            if(page == 2){
                                h5.innerHTML = "Rate a beer (2/5)";
                                form1.innerHTML = "";
                                page2();
                                button();  
                                listen();                      
                            }
                            if(page == 3){
                                h5.innerHTML = "Rate a beer (3/5) " + title2;
                                form1.innerHTML = "";
                                page3();
                                button();
                                listen();
                            }
                            if(page == 4){
                                h5.innerHTML = "Rate a beer (4/5)";
                                form1.innerHTML = "";
                                page2();
                                button();
                                listen();
                            }
                            if(page == 5){
                                h5.innerHTML = "Rate a beer (5/5)";
                                form1.innerHTML = "";
                                page2();
                                button();
                                listen();                  
                            }   
                        }
        
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>