
            <div class="container-fluid d-flex align-items-center flex-column bg-secondary" style=" padding:40px;">
                <!-- Titre de la degustation-->
                <h1 class="masthead2-heading text-uppercase mb-0">Titre de la degustation</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Nom du degustateur-->
                <p class="masthead2-subheading font-weight-light mb-0">Nom du degustateur - Titre de la bière - Type de la bière</p>
            </div>
<!-- Content Section-->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
                <!-- Content section -->
                <div class="">
                            <h3>Bottle Inspection <span class="text-uppercase margin-l-20">Finance</span></h3>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed tempor incdidunt ut laboret dolor magna ut consequat siad esqudiat dolor</p>
                </div>
     </div>
</section>
