
            <div class="container-fluid d-flex align-items-center flex-column bg-secondary" style=" padding:40px;">
                <!-- Titre de la degustation-->
                <h1 class="masthead2-heading text-uppercase mb-0">Titre de la degustation</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Nom du degustateur-->
                <p class="masthead2-subheading font-weight-light mb-0">Nom du degustateur - Titre de la bière - Type de la bière</p>
            </div>
<!-- Content Section-->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
    <!-- Content section -->
            <!-- Bottle Inspection -->
                <div class="">
                    <div class="row">
                       <h3 class="col-6">Bottle Inspection </h3>
                       <span class="col-2">Appreciation ou note</span>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
            <!-- Aroma -->
                <div class="">
                    <div class="row">
                       <h3 class="col-6">Arome </h3>
                       <strong class="col-2"><!-- Valeur --> /12</strong>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
            <!-- Appearance -->
               <div class="">
                    <div class="row">
                       <h3 class="col-6">Apparence </h3>
                       <strong class="col-2"><!-- Valeur --> /3</strong>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
              <!-- Flavor -->
               <div class="">
                    <div class="row">
                       <h3 class="col-6">Saveur </h3>
                       <strong class="col-2"><!-- Valeur --> /20</strong>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
               <!-- MouthFeel -->
                <div class="">
                    <div class="row">
                       <h3 class="col-6"> Sensation en bouche</h3>
                       <strong class="col-2"><!-- Valeur --> /5</strong>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
               <!-- Overall Impression -->
                  <div class="">
                    <div class="row">
                       <h3 class="col-6">Impression génerale </h3>
                       <strong class="col-2"><!-- Valeur --> /10</strong>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
                <!-- Descriptor definitions -->
                  <div class="">
                    <div class="row">
                       <h3 class="col-6">Description de la saveur</h3>
                    </div>
                        <p>
                           <!-- Commentaires -->
                        </p>
                </div>
                <!-- Stylistic Accuracy -->
                <div class="">
                     <div class="row">
                       <h3 class="col-6">Precision stylistique </h3>
                     </div>
                     <strong> <!-- Valeur --> </strong>
                </div>
                <!-- Technical Merit -->
                <div class="">
                     <div class="row">
                       <h3 class="col-6">Merite technique </h3>
                     </div>
                     <strong> <!-- Valeur --> </strong>
                </div>
                <!-- Intangibles -->
                <div class="">
                     <div class="row">
                       <h3 class="col-6">Intagibles </h3>
                     </div>
                     <strong> <!-- Valeur --> </strong>
                </div>
                <!-- Note Total -->
                <div class="">
                     <div class="row">
                         <h3 class="col-8">Note totale</h3>
                     <strong class="col-4"> <!-- Valeur --> /50</strong>
                     </div>
                     
                </div>




     </div>
</section>
