<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Informations</h4>
                </div>
                <!-- Action pour modifier le nom ou le prenom -->
                <form action="#" method="post">
                    <div class="row mt-2">
                        <div class="col-md-6"><label class="labels">Name</label><input type="text" class="form-control"
                                placeholder="first name" value=""></div>
                        <div class="col-md-6"><label class="labels">Surname</label><input type="text"
                                class="form-control" value="" placeholder="surname"></div>
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save
                                Profile</button></div>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <!-- Action pour modifier le password -->
                <form action="" method="post">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center experience">
                            <h4 class="text-right">Edit Password</h4>
                        </div><br>
                        <div class="form-floating mb-3 col-md-12">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                name="password">
                            <label for="floatingInput">Nouveau mot de passe</label>
                        </div>
                        <div class="form-floating mb-3 col-md-12">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                name="confirmPassword">
                            <label for="floatingInput">Confirmer le mot de passe</label>
                        </div>
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save
                                Password</button></div>
                </form>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="text-right">My tastings</h4>
        </div>
        <table class="table table-striped">

        </table>
    </div>
</div>
</div>
</div>