<style>
 input{
     padding:3px;
 }
</style>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-2 border-right">
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class="justify-content-between align-items-center mb-1">
                    <h4 class="text-center">Profile Informations</h4>
                </div>
                <!-- Action pour modifier le nom ou le prenom -->
                <form action="#" method="post">
                    <div class="row mt-2">
                        <div class="form-floating col-md-6">
                            <input type="text" class="form-control" placeholder="first name" value="" id="floatingInput">
                            <label for="floatingInput" >Name</label>
                            </div>
                        <div class="form-floating col-md-6">
                            <input type="text"class="form-control" value="" placeholder="surname" id="floatingInput">
                            <label for="floatingInput">Surname</label>
                        </div>
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save
                                Profile</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 border-right">
             </div>
             <div class="col-md-8">
                <!-- Action pour modifier le password -->
                <form action="" method="post">
                    <div class="p-3 py-5">
                        <div class="justify-content-between align-items-center experience">
                            <h4 class="text-center">Edit Password</h4>
                        </div><br>
                        <div class="row">
                                <div class="form-floating mb-3 col-md-6">
                                   <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                     name="password">
                                   <label for="floatingInput">Nouveau mot de passe</label>
                                </div>
                                <div class="form-floating mb-3 col-md-6">
                                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"
                                    name="confirmPassword">
                                    <label for="floatingInput">Confirmer le mot de passe</label>
                                </div>
                        </div>
                        
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save
                                Password</button></div>
                </form>
            </div>
        </div>
</div>
</div>
</div>
